# Register at https://openweathermap.org to get your API key
api_key = "dc3334058aeadd8467b3d56a883f978d"

# This is for Paris, find your city at https://openweathermap.org
# The id will be the last part of the URL
city_id = "2988507"

# Display settings
units = "metric"
display_symbol = "°C"
