#!/bin/sh

# shortcuts
alias ll="ls -lF --group-directories-first"
alias l="ls -alF --group-directories-first"
alias tr="exa -lhT"
alias c="clear"
alias weather="curl wttr.in/Paris"
alias r="ranger"
alias v="vim"
alias yt="youtube-dl"
alias g="git"
alias s="subl"
alias m="neomutt"
alias ms="mpv --shuffle --background=#00000000 "
alias n="ncmpcpp"
alias cal="calcurse"
alias vt="vtop"
alias hal="ssh root@slashome.io"
alias pbcopy='xsel --clipboard --input'
alias pbpaste='xsel --clipboard --output'
alias subl='subl3'
alias lg='lazygit'
alias gpo='git push origin'

alias cover="cd ~/scripts/ && urxvt -b 0 -e sh -c ./cover.sh"

# system
alias updot="cd ~/dotfiles && git pull && ./install.sh"

# trizen
alias pacs="yay -Ss"                                           # Search
alias paci="yay -S --noconfirm"                                # Install
alias pacr="yay -R"                                            # Remove
alias pacu=" yay -Syyu --noconfirm && yay -Syyua --noconfirm"  # Update
alias pacc="yay -Sc --noconfirm"                               # Clean
alias pacl="yay -Qku && pacman -Qku"                           # List packages to update
alias pacli="yay -Qae"                                         # List installed packages
alias pack="sudo pacman-key --keyserver pgp.mit.edu -r"        # Add unknown key
alias pac-reset-keys="sudo rm -rf /etc/pacman.d/gnupg && sudo pacman-key --init && sudo pacman-key --populate archlinux"

