#!/usr/bin/env bash
IMG=$(ls ~/.cache/.wallpie.*)
convert $IMG \
  -resize 1920x1080\! \
  ~/.cache/lock.jpg
i3lock -t -i ~/.cache/lock.jpg

#i3lock --color=000000
exit

# Author : Pavan Jadhaw
# Github Profile : https://github.com/pavanjadhaw
# Project Repository : https://github.com/pavanjadhaw/betterlockscreen

# create folder in ~/.cache/i3lock directory
folder="$HOME/.cache/i3lock"

# ratio for rectangle to be drawn for time background on lockscreen
# Original Image
orig_wall="$folder/wall.png"

# Versions (from here)
# You can use these images to set different versions as wallpaper
# lockscreen background.
resized="$folder/resized.png" # resized image for your resolution

# images to be used as wallpaper
dim="$folder/dim.png" # image with subtle overlay of black
blur="$folder/blur.png" # blurred version
dimblur="$folder/dimblur.png"

# lockscreen images (images to be used as lockscreen background)
l_resized="$folder/l_resized.png"
l_dim="$folder/l_dim.png"
l_blur="$folder/l_blur.png"
l_dimblur="$folder/l_dimblur.png"


prelock() {
	pkill -u "$USER" -USR1 dunst
}

lock() {
	#$1 image path
	letterEnteredColor=d23c3dff
	letterRemovedColor=d23c3dff
	passwordCorrect=00000000
	passwordIncorrect=d23c3dff
	background=00000000
	foreground=ffffffff
	i3lock \
		-t -i "$1" \
		--timepos="110:h-70" \
		--datepos="135:h-45" \
		--clock --datestr "Type password to unlock..." \
		--insidecolor=$background --ringcolor=$foreground --line-uses-inside \
		--keyhlcolor=$letterEnteredColor --bshlcolor=$letterRemovedColor --separatorcolor=$background \
		--insidevercolor=$passwordCorrect --insidewrongcolor=$passwordIncorrect \
		--ringvercolor=$foreground --ringwrongcolor=$foreground --indpos="x+280:h-70" \
		--radius=20 --ring-width=4 --veriftext="" --wrongtext="" \
		--verifcolor="$foreground" --timecolor="$foreground" --datecolor="$foreground" \
        --noinputtext="" \
		--force-clock
}

postlock() {
	pkill -u "$USER" -USR2 dunst
}

prelock
lock $l_dimblur
postlock
