#!/bin/sh

# shortcuts
alias ll="ls -lF"
alias l="ls -alF"
alias c="clear"
alias v="vim"
alias g="git"

alias hal="ssh root@hal9000.im"

# system
alias updot="cd ~/dotfiles && git pull && ./install.sh"

# trizen
alias pacs="trizen -Ss"                                 # Search
alias paci="trizen -S --noconfirm --noedit"             # Install
alias pacr="trizen -R"                                  # Remove
alias pacu="trizen -Syyu --noconfirm --noedit"          # Update
alias pacc="trizen -Sc --noconfirm"                     # Clean
alias pacl="trizen -Qku"                                # List packages to update
alias pacli="trizen -Qae"                               # List installed packages
alias pack="sudo pacman-key --keyserver pgp.mit.edu -r" # Add unknown key
alias pac-reset-keys="sudo rm -rf /etc/pacman.d/gnupg && sudo pacman-key --init && sudo pacman-key --populate archlinux"
